playlist = {
    "NPO Radio 1"               : "http://icecast.omroep.nl/radio1-bb-mp3",
    "NPO Radio 2"               : "http://icecast.omroep.nl/radio2-bb-mp3",
    "NPO Radio 3"               : "http://icecast.omroep.nl/3fm-bb-mp3",
    "NPO Radio 3 Alternative"   : "http://icecast.omroep.nl/3fm-alternative-mp3",
    "FunX NL"                   : "http://icecast.omroep.nl/funx-bb-mp3",
    "FunX Utrecht"              : "http://icecast.omroep.nl/funx-utrecht-bb-mp3",
    "Funx Reggae"               : "http://icecast.omroep.nl/funx-reggae-bb-mp3",
    "100% NL"                   : "http://stream.100p.nl/100pctnl.mp3",
    "192 Radio"                 : "http://188.213.230.36:8030/stream",
    "40UP Radio"                : "http://40upstream.live-streams.nl/40up1",
    "Radio 538"                 : "http://19093.live.streamtheworld.com/RADIO538.mp3",
    "Radio 538 Hitzone"         : "http://playerservices.streamtheworld.com/api/livestream-redirect/TLPSTR11.mp3",
    "Radio 538 Nonstop"         : "http://playerservices.streamtheworld.com/api/livestream-redirect/TLPSTR09.mp3",
    "Arrow Classic Rock"        : "http://91.221.151.155/;?.mp3",
    "BNR Nieuwsradio"           : "http://icecast-bnr.cdp.triple-it.nl/bnr_mp3_96_04.m3u",
    "Christmas 24"              : "http://212.237.51.88/;",
    "Disco classic radio"       : "http://discoclassicradio.shoutcaststream.com:8312/stream",
    "Radio Veronica"            : "http://www.radioveronica.nl/player/radio-veronica.pls",
    "Radio Veronica 80's"       : "http://www.radioveronica.nl/player/veronica-80s-hits.pls",
    "Q-Music"                   : "http://icecast-qmusic.cdp.triple-it.nl/Qmusic_nl_live_96.mp3",
    "Q-Music Nonstop"           : "http://icecast-qmusicnl-cdp.triple-it.nl/Qmusic_nl_nonstop_96.mp3",
    "Radio 10"                  : "http://playerservices.streamtheworld.com/api/livestream-redirect/RADIO10",
    "Radio 10 Top 4000"         : "http://playerservices.streamtheworld.com/api/livestream-redirect/TLPSTR24",
    "Radio 10 Number 1"         : "http://playerservices.streamtheworld.com/api/livestream-redirect/TLPSTR14",
    "Radio 10 80's"             : "http://playerservices.streamtheworld.com/api/livestream-redirect/TLPSTR20",
    "Sky Radio"                 : "http://www.skyradio.nl/player/skyradio.pls",
    "Sky Radio Hits"            : "http://www.skyradio.nl/player/skyradio-hits.pls",
    "Sky Radio Christmas"       : "http://20103.live.streamtheworld.com/SRGSTR08AAC.aac",
    "Sky Radio 80's"            : "http://www.skyradio.nl/player/skyradio-80s.pls",
    "Radio M Utrecht"           : "http://icecast.omroep.nl/rtvutrecht-radio-m-bb-mp3.m3u",
    "Omroep Zeeland"            : "http://livestream.zeelandnet.nl:8000/omroepzeeland_radio",
    "Omroep Tholen"             : "https://www.omroeptholen.nl/public/upload/files/ot.m3u"
}
